# generated by datamodel-codegen:
#   filename:  activity.schema.json

from __future__ import annotations
from enum import Enum
from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)
from typing import Literal
from datetime import date


class Type(Enum):
    running = "running"
    trail_running = "trail_running"
    treadmill_running = "treadmill_running"
    track_running = "track_running"
    indoor_running = "indoor_running"
    other = "other"


class DateTimeUtc(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(..., description="ISO 8601 datetime in UTC.")


class Sex(Enum):
    male = "male"
    female = "female"
    other = "other"


class Units(Enum):
    metric = "metric"
    imperial = "imperial"


class RaceType(Enum):
    field_5k = "5k"
    field_10k = "10k"
    half_marathon = "half_marathon"
    marathon = "marathon"
    ultra = "ultra"


class Methodology(Enum):
    daniels_vdot = "daniels_vdot"
    pfitzinger_lt = "pfitzinger_lt"
    hanson = "hanson"
    polarized_80_20 = "polarized_80_20"
    hybrid = "hybrid"


class WorkoutType(Enum):
    easy = "easy"
    long = "long"
    tempo = "tempo"
    threshold = "threshold"
    intervals = "intervals"
    fartlek = "fartlek"
    hills = "hills"
    race_pace = "race_pace"
    recovery = "recovery"
    rest = "rest"
    strides = "strides"
    test = "test"


class WorkoutStatus(Enum):
    planned = "planned"
    completed = "completed"
    missed = "missed"
    moved = "moved"
    skipped = "skipped"


class MovedReason(Enum):
    missed = "missed"
    user_edit = "user_edit"
    hrv = "hrv"
    sleep = "sleep"
    load = "load"
    rhr = "rhr"
    performance = "performance"
    replan = "replan"


class Feeling(Enum):
    great = "great"
    good = "good"
    flat = "flat"
    sore = "sore"
    wrecked = "wrecked"


class AgentName(Enum):
    planner = "planner"
    adapter = "adapter"


class AgentTrigger(Enum):
    onboarding = "onboarding"
    manual_regenerate = "manual_regenerate"
    weekly_review = "weekly_review"
    missed_workout = "missed_workout"
    hrv_drop = "hrv_drop"
    sleep_low = "sleep_low"
    load_breach = "load_breach"
    rhr_high = "rhr_high"
    performance_drift = "performance_drift"
    race_change = "race_change"


class HrZone(RootModel[conint(ge=1, le=5)]):
    root: conint(ge=1, le=5) = Field(..., description="Heart-rate zone (1=recovery, 5=anaerobic).")


class PaceSecPerKm(RootModel[conint(ge=120, le=900)]):
    root: conint(ge=120, le=900) = Field(
        ..., description="Pace expressed as seconds per kilometre. 120=2:00/km, 900=15:00/km."
    )


class PaceTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["pace"]
    minSecPerKm: PaceSecPerKm
    maxSecPerKm: PaceSecPerKm


class HrTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["hrZone"]
    zone: HrZone


class RpeTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["rpe"]
    minRpe: conint(ge=1, le=10)
    maxRpe: conint(ge=1, le=10)


class Target(RootModel[PaceTarget | HrTarget | RpeTarget]):
    root: PaceTarget | HrTarget | RpeTarget


class DateOnly(RootModel[date]):
    root: date = Field(
        ..., description="ISO 8601 calendar date in the user's local timezone, e.g. 2026-05-04."
    )


class IsoWeek(RootModel[constr(pattern=r"^\d{4}-W\d{2}$")]):
    root: constr(pattern=r"^\d{4}-W\d{2}$") = Field(
        ..., description="ISO 8601 week, e.g. 2026-W19."
    )


class Interval(BaseModel):
    indexInActivity: conint(ge=0) | None = None
    durationSec: int | None = None
    distanceM: float | None = None
    avgPaceSecPerKm: PaceSecPerKm | None = None
    avgHr: int | None = None


class Activity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    uid: str
    garminActivityId: str
    startedAt: DateTimeUtc
    localDate: DateOnly | None = None
    type: Type = Field(..., description="Garmin activity type, normalized.")
    durationSec: conint(ge=0)
    distanceM: confloat(ge=0.0)
    avgPaceSecPerKm: PaceSecPerKm | None = None
    avgHr: conint(ge=30, le=230) | None = None
    maxHr: conint(ge=30, le=230) | None = None
    elevationGainM: float | None = None
    calories: int | None = None
    trainingEffectAerobic: confloat(ge=0.0, le=5.0) | None = None
    trainingEffectAnaerobic: confloat(ge=0.0, le=5.0) | None = None
    trainingLoadScore: float | None = None
    vo2max: float | None = None
    perceivedEffort: conint(ge=1, le=10) | None = None
    feeling: Feeling | None = None
    intervals: list[Interval] | None = Field(
        None, description="Lap or interval breakdown if available."
    )
    matchedWorkoutId: str | None = Field(
        None, description="If matched to a planned workout, its ID."
    )
    syncedAt: DateTimeUtc | None = None
