# generated by datamodel-codegen:
#   filename:  agent-run.schema.json

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, conint, constr
from enum import Enum
from typing import Any, Literal
from datetime import date


class InputSummary(BaseModel):
    athleteProfileHash: str | None = None
    planId: str | None = None
    windowDays: int | None = None


class RulesEngineDecision(BaseModel):
    code: str | None = None
    decision: str | None = None
    details: str | None = None


class Op(Enum):
    move = "move"
    modify = "modify"
    replace = "replace"
    insert_rest = "insert_rest"
    skip = "skip"


class OutputPatch(BaseModel):
    op: Op | None = None
    workoutId: str | None = None
    before: dict[str, Any] | None = None
    after: dict[str, Any] | None = None
    reason: str | None = None


class Status(Enum):
    success = "success"
    schema_invalid = "schema_invalid"
    guardrail_violation = "guardrail_violation"
    error = "error"


class AgentName(Enum):
    planner = "planner"
    adapter = "adapter"


class Sex(Enum):
    male = "male"
    female = "female"
    other = "other"


class Units(Enum):
    metric = "metric"
    imperial = "imperial"


class RaceType(Enum):
    field_5k = "5k"
    field_10k = "10k"
    half_marathon = "half_marathon"
    marathon = "marathon"
    ultra = "ultra"


class Methodology(Enum):
    daniels_vdot = "daniels_vdot"
    pfitzinger_lt = "pfitzinger_lt"
    hanson = "hanson"
    polarized_80_20 = "polarized_80_20"
    hybrid = "hybrid"


class WorkoutType(Enum):
    easy = "easy"
    long = "long"
    tempo = "tempo"
    threshold = "threshold"
    intervals = "intervals"
    fartlek = "fartlek"
    hills = "hills"
    race_pace = "race_pace"
    recovery = "recovery"
    rest = "rest"
    strides = "strides"
    test = "test"


class WorkoutStatus(Enum):
    planned = "planned"
    completed = "completed"
    missed = "missed"
    moved = "moved"
    skipped = "skipped"


class MovedReason(Enum):
    missed = "missed"
    user_edit = "user_edit"
    hrv = "hrv"
    sleep = "sleep"
    load = "load"
    rhr = "rhr"
    performance = "performance"
    replan = "replan"


class Feeling(Enum):
    great = "great"
    good = "good"
    flat = "flat"
    sore = "sore"
    wrecked = "wrecked"


class AgentTrigger(Enum):
    onboarding = "onboarding"
    manual_regenerate = "manual_regenerate"
    weekly_review = "weekly_review"
    missed_workout = "missed_workout"
    hrv_drop = "hrv_drop"
    sleep_low = "sleep_low"
    load_breach = "load_breach"
    rhr_high = "rhr_high"
    performance_drift = "performance_drift"
    race_change = "race_change"


class HrZone(RootModel[conint(ge=1, le=5)]):
    root: conint(ge=1, le=5) = Field(..., description="Heart-rate zone (1=recovery, 5=anaerobic).")


class PaceSecPerKm(RootModel[conint(ge=120, le=900)]):
    root: conint(ge=120, le=900) = Field(
        ..., description="Pace expressed as seconds per kilometre. 120=2:00/km, 900=15:00/km."
    )


class PaceTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["pace"]
    minSecPerKm: PaceSecPerKm
    maxSecPerKm: PaceSecPerKm


class HrTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["hrZone"]
    zone: HrZone


class RpeTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["rpe"]
    minRpe: conint(ge=1, le=10)
    maxRpe: conint(ge=1, le=10)


class Target(RootModel[PaceTarget | HrTarget | RpeTarget]):
    root: PaceTarget | HrTarget | RpeTarget


class DateOnly(RootModel[date]):
    root: date = Field(
        ..., description="ISO 8601 calendar date in the user's local timezone, e.g. 2026-05-04."
    )


class DateTimeUtc(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(..., description="ISO 8601 datetime in UTC.")


class IsoWeek(RootModel[constr(pattern=r"^\d{4}-W\d{2}$")]):
    root: constr(pattern=r"^\d{4}-W\d{2}$") = Field(
        ..., description="ISO 8601 week, e.g. 2026-W19."
    )


class AgentRun(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    uid: str
    agent: AgentName
    trigger: AgentTrigger
    model: str = Field(..., description="e.g. gemini-2.5-pro, gemini-2.5-flash.")
    promptVersion: str | None = Field(None, description="Version tag of the prompt template used.")
    inputSummary: InputSummary | None = Field(
        None, description="Hashes/summaries of inputs (no raw PII), for traceability."
    )
    rulesEngineDecisions: list[RulesEngineDecision] | None = Field(
        None, description="Output of the deterministic rules engine that ran before the LLM."
    )
    outputPatches: list[OutputPatch] | None = Field(
        None,
        description="Patches the agent applied. Empty for planner runs (which use propose_plan).",
    )
    newPlanId: str | None = Field(None, description="Set if the planner produced a new plan.")
    tokensIn: int | None = None
    tokensOut: int | None = None
    costUsd: float | None = None
    latencyMs: int | None = None
    status: Status
    errorMessage: str | None = None
    createdAt: DateTimeUtc
