# generated by datamodel-codegen:
#   filename:  athlete-profile.schema.json

from __future__ import annotations
from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)
from enum import Enum
from typing import Literal
from datetime import date as date_aliased


class WeeklyMileageKm(BaseModel):
    last4w: confloat(ge=0.0) | None = None
    last12w: confloat(ge=0.0) | None = None


class EasyHardSplit(BaseModel):
    easyPct: confloat(ge=0.0, le=100.0) | None = None
    hardPct: confloat(ge=0.0, le=100.0) | None = None


class HrZones(BaseModel):
    z1: int | None = None
    z2: int | None = None
    z3: int | None = None
    z4: int | None = None
    z5: int | None = None
    max: int | None = None
    resting: int | None = None


class GarminRacePredictor(BaseModel):
    fiveKSec: int | None = None
    tenKSec: int | None = None
    halfMarathonSec: int | None = None
    marathonSec: int | None = None


class TrainingLoad(BaseModel):
    ctl: float | None = Field(None, description="Chronic training load (42d EWMA).")
    atl: float | None = Field(None, description="Acute training load (7d EWMA).")
    tsb: float | None = Field(None, description="Training stress balance (CTL - ATL).")
    acwr: float | None = Field(None, description="Acute:chronic workload ratio.")


class RecoveryPattern(BaseModel):
    hrvBaseline: float | None = None
    hrvSd: float | None = None
    rhrBaseline: int | None = None
    avgSleepHours: float | None = None


class PreferredTrainingDay(Enum):
    sun = "sun"
    mon = "mon"
    tue = "tue"
    wed = "wed"
    thu = "thu"
    fri = "fri"
    sat = "sat"


class LongRunDay(Enum):
    sun = "sun"
    mon = "mon"
    tue = "tue"
    wed = "wed"
    thu = "thu"
    fri = "fri"
    sat = "sat"


class WeeklyReviewDay(Enum):
    sun = "sun"
    mon = "mon"
    tue = "tue"
    wed = "wed"
    thu = "thu"
    fri = "fri"
    sat = "sat"


class Sex(Enum):
    male = "male"
    female = "female"
    other = "other"


class Units(Enum):
    metric = "metric"
    imperial = "imperial"


class RaceType(Enum):
    field_5k = "5k"
    field_10k = "10k"
    half_marathon = "half_marathon"
    marathon = "marathon"
    ultra = "ultra"


class Methodology(Enum):
    daniels_vdot = "daniels_vdot"
    pfitzinger_lt = "pfitzinger_lt"
    hanson = "hanson"
    polarized_80_20 = "polarized_80_20"
    hybrid = "hybrid"


class WorkoutType(Enum):
    easy = "easy"
    long = "long"
    tempo = "tempo"
    threshold = "threshold"
    intervals = "intervals"
    fartlek = "fartlek"
    hills = "hills"
    race_pace = "race_pace"
    recovery = "recovery"
    rest = "rest"
    strides = "strides"
    test = "test"


class WorkoutStatus(Enum):
    planned = "planned"
    completed = "completed"
    missed = "missed"
    moved = "moved"
    skipped = "skipped"


class MovedReason(Enum):
    missed = "missed"
    user_edit = "user_edit"
    hrv = "hrv"
    sleep = "sleep"
    load = "load"
    rhr = "rhr"
    performance = "performance"
    replan = "replan"


class Feeling(Enum):
    great = "great"
    good = "good"
    flat = "flat"
    sore = "sore"
    wrecked = "wrecked"


class AgentName(Enum):
    planner = "planner"
    adapter = "adapter"


class AgentTrigger(Enum):
    onboarding = "onboarding"
    manual_regenerate = "manual_regenerate"
    weekly_review = "weekly_review"
    missed_workout = "missed_workout"
    hrv_drop = "hrv_drop"
    sleep_low = "sleep_low"
    load_breach = "load_breach"
    rhr_high = "rhr_high"
    performance_drift = "performance_drift"
    race_change = "race_change"


class HrZone(RootModel[conint(ge=1, le=5)]):
    root: conint(ge=1, le=5) = Field(..., description="Heart-rate zone (1=recovery, 5=anaerobic).")


class PaceSecPerKm(RootModel[conint(ge=120, le=900)]):
    root: conint(ge=120, le=900) = Field(
        ..., description="Pace expressed as seconds per kilometre. 120=2:00/km, 900=15:00/km."
    )


class PaceTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["pace"]
    minSecPerKm: PaceSecPerKm
    maxSecPerKm: PaceSecPerKm


class HrTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["hrZone"]
    zone: HrZone


class RpeTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["rpe"]
    minRpe: conint(ge=1, le=10)
    maxRpe: conint(ge=1, le=10)


class Target(RootModel[PaceTarget | HrTarget | RpeTarget]):
    root: PaceTarget | HrTarget | RpeTarget


class DateOnly(RootModel[date_aliased]):
    root: date_aliased = Field(
        ..., description="ISO 8601 calendar date in the user's local timezone, e.g. 2026-05-04."
    )


class DateTimeUtc(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(..., description="ISO 8601 datetime in UTC.")


class IsoWeek(RootModel[constr(pattern=r"^\d{4}-W\d{2}$")]):
    root: constr(pattern=r"^\d{4}-W\d{2}$") = Field(
        ..., description="ISO 8601 week, e.g. 2026-W19."
    )


class RecentRace(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    raceType: RaceType
    date: DateOnly
    finishTimeSec: conint(ge=600, le=100000)
    garminActivityId: str | None = None


class Self(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    age: conint(ge=13, le=100)
    sex: Sex
    weightKg: confloat(ge=30.0, le=250.0)
    heightCm: confloat(ge=100.0, le=230.0) | None = None
    timezone: str = Field(..., description="IANA timezone, e.g. Asia/Jerusalem.")
    injuryNotes: constr(max_length=2000) | None = None
    recentRaces: list[RecentRace] | None = None


class Fitness(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    vo2max: confloat(ge=20.0, le=90.0) | None = None
    weeklyMileageKm: WeeklyMileageKm | None = Field(
        None, description="Trailing 4-week and 12-week averages of weekly running distance."
    )
    longestRecentRunKm: confloat(ge=0.0) | None = None
    easyHardSplit: EasyHardSplit | None = Field(
        None,
        description="Percentage of time in HR zones 1-2 (easy) vs 3+ (hard) over the last 90 days.",
    )
    hrZones: HrZones | None = Field(
        None,
        description="User HR zones in bpm (lower bounds). Either Garmin-provided or computed from max HR.",
    )
    ltHr: int | None = Field(
        None, description="Lactate threshold heart rate (Garmin-derived or estimated)."
    )
    thresholdPaceSecPerKm: PaceSecPerKm | None = None
    garminRacePredictor: GarminRacePredictor | None = Field(
        None, description="Garmin's race time predictions, if available."
    )
    trainingLoad: TrainingLoad | None = Field(
        None, description="Most recent training-load metrics."
    )
    recoveryPattern: RecoveryPattern | None = Field(
        None, description="Typical recovery profile, used to calibrate adaptation thresholds."
    )


class Preferences(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    units: Units
    trainingDaysPerWeek: conint(ge=3, le=7)
    preferredTrainingDays: list[PreferredTrainingDay] = Field(..., max_length=7, min_length=3)
    longRunDay: LongRunDay
    weeklyReviewHourLocal: conint(ge=0, le=23) | None = 18
    weeklyReviewDay: WeeklyReviewDay | None = "sat"


class AthleteProfile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    uid: constr(min_length=1)
    self: Self
    fitness: Fitness = Field(
        ...,
        description="Derived from the last 90 days of Garmin data. All fields are nullable if insufficient data.",
    )
    preferences: Preferences
    computedAt: DateTimeUtc
