# generated by datamodel-codegen:
#   filename:  plan-output.schema.json

from __future__ import annotations
from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    confloat,
    conint,
    constr,
)
from enum import Enum
from typing import Literal
from datetime import date


class SelfCritique(BaseModel):
    weeklyVolumeIncreaseOk: bool = Field(
        ...,
        description="True iff every week's volume grows by <=10% vs the prior, except prescribed deload bumps.",
    )
    tapersCorrectly: bool
    noBackToBackHard: bool
    longRunCapOk: bool = Field(
        ..., description="True iff long run is <=35% of weekly volume in every week."
    )
    comments: constr(max_length=1000)


class RaceType(Enum):
    field_5k = "5k"
    field_10k = "10k"
    half_marathon = "half_marathon"
    marathon = "marathon"
    ultra = "ultra"


class Sex(Enum):
    male = "male"
    female = "female"
    other = "other"


class Units(Enum):
    metric = "metric"
    imperial = "imperial"


class Methodology(Enum):
    daniels_vdot = "daniels_vdot"
    pfitzinger_lt = "pfitzinger_lt"
    hanson = "hanson"
    polarized_80_20 = "polarized_80_20"
    hybrid = "hybrid"


class WorkoutType(Enum):
    easy = "easy"
    long = "long"
    tempo = "tempo"
    threshold = "threshold"
    intervals = "intervals"
    fartlek = "fartlek"
    hills = "hills"
    race_pace = "race_pace"
    recovery = "recovery"
    rest = "rest"
    strides = "strides"
    test = "test"


class WorkoutStatus(Enum):
    planned = "planned"
    completed = "completed"
    missed = "missed"
    moved = "moved"
    skipped = "skipped"


class MovedReason(Enum):
    missed = "missed"
    user_edit = "user_edit"
    hrv = "hrv"
    sleep = "sleep"
    load = "load"
    rhr = "rhr"
    performance = "performance"
    replan = "replan"


class Feeling(Enum):
    great = "great"
    good = "good"
    flat = "flat"
    sore = "sore"
    wrecked = "wrecked"


class AgentName(Enum):
    planner = "planner"
    adapter = "adapter"


class AgentTrigger(Enum):
    onboarding = "onboarding"
    manual_regenerate = "manual_regenerate"
    weekly_review = "weekly_review"
    missed_workout = "missed_workout"
    hrv_drop = "hrv_drop"
    sleep_low = "sleep_low"
    load_breach = "load_breach"
    rhr_high = "rhr_high"
    performance_drift = "performance_drift"
    race_change = "race_change"


class HrZone(RootModel[conint(ge=1, le=5)]):
    root: conint(ge=1, le=5) = Field(..., description="Heart-rate zone (1=recovery, 5=anaerobic).")


class PaceSecPerKm(RootModel[conint(ge=120, le=900)]):
    root: conint(ge=120, le=900) = Field(
        ..., description="Pace expressed as seconds per kilometre. 120=2:00/km, 900=15:00/km."
    )


class PaceTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["pace"]
    minSecPerKm: PaceSecPerKm
    maxSecPerKm: PaceSecPerKm


class HrTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["hrZone"]
    zone: HrZone


class RpeTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["rpe"]
    minRpe: conint(ge=1, le=10)
    maxRpe: conint(ge=1, le=10)


class Target(RootModel[PaceTarget | HrTarget | RpeTarget]):
    root: PaceTarget | HrTarget | RpeTarget


class DateOnly(RootModel[date]):
    root: date = Field(
        ..., description="ISO 8601 calendar date in the user's local timezone, e.g. 2026-05-04."
    )


class DateTimeUtc(RootModel[AwareDatetime]):
    root: AwareDatetime = Field(..., description="ISO 8601 datetime in UTC.")


class IsoWeek(RootModel[constr(pattern=r"^\d{4}-W\d{2}$")]):
    root: constr(pattern=r"^\d{4}-W\d{2}$") = Field(
        ..., description="ISO 8601 week, e.g. 2026-W19."
    )


class Phase(Enum):
    base = "base"
    build = "build"
    peak = "peak"
    taper = "taper"
    race = "race"
    recovery = "recovery"


class WeeklyStructureItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    isoWeek: IsoWeek
    phase: Phase
    targetVolumeKm: confloat(ge=0.0)
    qualitySessions: conint(ge=0, le=5)
    isDeload: bool | None = False


class WeeklyStructure(RootModel[list[WeeklyStructureItem]]):
    root: list[WeeklyStructureItem] = Field(
        ...,
        description="High-level macrocycle: one entry per training week, in chronological order.",
    )


class Step1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["duration"]
    seconds: conint(ge=1, le=36000)
    target: Target | None = None
    note: constr(max_length=200) | None = None


class Step2(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["distance"]
    meters: conint(ge=50, le=100000)
    target: Target | None = None
    note: constr(max_length=200) | None = None


class Step3(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["lap_button"]
    target: Target | None = None
    note: constr(max_length=200) | None = None


class Step(RootModel[Step1 | Step2 | Step3]):
    root: Step1 | Step2 | Step3


class RepeatBlock(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["repeat"]
    repeat: conint(ge=2, le=50)
    steps: list[Step] = Field(..., min_length=1)


class RpeRangeItem(RootModel[conint(ge=1, le=10)]):
    root: conint(ge=1, le=10)


class Targets(BaseModel):
    rpeRange: list[RpeRangeItem] | None = Field(None, max_length=2, min_length=2)


class Plan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    raceType: RaceType
    raceName: constr(max_length=200) | None = None
    raceDate: DateOnly
    goalTimeSec: int | None = None
    goalPaceSecPerKm: PaceSecPerKm | None = None
    methodology: Methodology
    methodologyRationale: constr(min_length=50, max_length=1500)
    weeklyStructure: WeeklyStructure


class Structure(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    warmup: Step | None = None
    mainSteps: list[Step | RepeatBlock] = Field(..., min_length=1)
    cooldown: Step | None = None


class Workout(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    scheduledDate: DateOnly
    type: WorkoutType
    title: str
    description: str | None = None
    estimatedDurationSec: int
    structure: Structure
    targets: Targets | None = None


class PlannerAgentOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    plan: Plan
    workouts: list[Workout] = Field(
        ...,
        description="Every day from start_date to race_date inclusive must appear, either as a training workout or as a rest day (type=rest).",
        min_length=1,
    )
    selfCritique: SelfCritique = Field(
        ...,
        description="Required self-check the planner must complete before returning. Used as a guard against obvious errors.",
    )
